before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'command -v ssh-agent >/dev/null || ( apt update -y && apt install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Adding known hosts
  ##
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

update_code:
  stage: deploy
  tags:
    - shell
  script:
    - scp -P 4022 -r * ${TEST_SERVER}:/home/ubuntu/wordpress/webs/${PROJECT}

update_db:
  stage: deploy
  tags:
    - shell
  script:
    - ssh -p 4022 ${TEST_SERVER} "cd wordpress/scripts && ./update_db.sh ${PROJECT} ${PREFIX}"
  only:
    changes:
      - "*.sql"